export const PAGE_MODALS_NAMES = {
  MOVIE_TYPES: {
    APPEND: "MODAL-MOVIE-TYPES-APPEND",
    DELETE: "MODAL-MOVIE-TYPES-DELETE",
  },
  GENRES: {
    APPEND: "MODAL-GENRES-APPEND",
    DELETE: "MODAL-GENRES-DELETE",
  },
};
