export const PAGE_MODALS_NAMES = {
  MOVIES: {
    APPEND: "MODAL-MOVIE-APPEND",
    DELETE: "MODAL-MOVIE-DELETE",
  },
  MOVIE_TYPES: {
    APPEND: "MODAL-MOVIE-TYPES-APPEND",
    DELETE: "MODAL-MOVIE-TYPES-DELETE",
  },
  GENRES: {
    APPEND: "MODAL-GENRES-APPEND",
    DELETE: "MODAL-GENRES-DELETE",
  },
  COUNTRIES: {
    APPEND: "MODAL-COUNTRY-APPEND",
    DELETE: "MODAL-COUNTRY-DELETE",
  },
  ACTORS: {
    APPEND: "MODAL-ACTOR-APPEND",
    DELETE: "MODAL-ACTOR-DELETE",
  },
  DIRECTORS: {
    APPEND: "MODAL-DIRECTOR-APPEND",
    DELETE: "MODAL-DIRECTOR-DELETE",
  },
};
