export const ROUTES_NAMES = {
  DASHBOARD: {
    MAIN: "DASHBOARD-MAIN",
    STATISTIC: "DASHBOARD-STATISTIC",
    ACCOUNTS: {
      LIST: "DASHBOARD-USERS-LIST",
      EDIT: "DASHBOARD-USERS-EDIT",
    },
  },
};
