export const ROUTES_NAMES = {
  DASHBOARD: {
    MAIN: "DASHBOARD-MAIN",
    STATISTIC: "DASHBOARD-STATISTIC",
    ACCOUNTS: {
      MAIN: "DASHBOARD-ACCOUNTS-MIAN",
      LIST: "DASHBOARD-ACCOUNTS-LIST",
      EDIT: "DASHBOARD-ACCOUNTS-EDIT",
    },
    MOVIESTER: {
      MOVIES: {
        MAIN: "DASHBOARD-MOVIESTER-MOVIES-MIAN",
        LIST: "DASHBOARD-MOVIESTER-MOVIES-LIST",
        EDIT: "DASHBOARD-MOVIESTER-MOVIES-EDIT",
      },
      MOVIE_TYPES: {
        MAIN: "DASHBOARD-MOVIESTER-MOVIE-TYPES-MIAN",
        LIST: "DASHBOARD-MOVIESTER-MOVIE-TYPES-LIST",
        EDIT: "DASHBOARD-MOVIESTER-MOVIE-TYPES-EDIT",
      },
      GENRES: {
        MAIN: "DASHBOARD-MOVIESTER-GENRES-MIAN",
        LIST: "DASHBOARD-MOVIESTER-GENRES-LIST",
        EDIT: "DASHBOARD-MOVIESTER-GENRES-EDIT",
      },
    },
  },
};
